blank_issues_enabled: false
contact_links:
- name: '📚 Create an Issue'
  about: You will be redirected to wso2/streaming-integrator repository where the issues are reported including Streaming Integrator Tooling related issues.
  url: https://github.com/wso2/streaming-integrator/issues/new/choose
- name: '💬 Slack Channel'
  url: 'https://apim-slack.wso2.com/'
  about: |
    Chat with the community to get quick clarifications for your questions.
